name: LightBP
version: '${project.version}'
main: org.satellite.dev.progiple.lightbp.LightBP
api-version: '1.16'
depend:
  - LunaSpring
  - NBTAPI
  - WorldGuard
softdepend:
  - PlaceholderAPI
commands:
  lightbp:
    usage: /lpb reload/addExp/setExp/addLevel/setLevel <player> <amount>
    aliases:
      - bp
      - lbp
      - lightbattlepass
      - lpass
      - bpass
      - pass
      - lbpass
      - battlep
      - battlepass
  toggleexp:
    aliases:
      - te
      - toggle
      - bptoggle
      - exptoggle
      - et
permissions:
  lightbp.admin:
    default: op
  lightbp.premium:
    default: false